### ISSUE TITLE
Have problem when npm run build-prod

### ISSUE THREAD

**Issue by abaykerimov** [atais/ng2-eonasdan-datetimepicker#26]
**ERROR in Error: Metadata version mismatch for module C:/projects/LFM/node_modules/ng2-eonasdan-datetimepicker/node_modules/@angular/core/core.d.ts, found versi
on 4, expected 3**
    at StaticSymbolResolver.getModuleMetadata (C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:25748:34)
    at StaticSymbolResolver._createSymbolsOf (C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:25536:46)
    at StaticSymbolResolver.getSymbolsOf (C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:25517:14)
    at C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:24376:30
    at Array.forEach (native)
    at extractProgramSymbols (C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:24375:79)
    at AotCompiler.analyzeModulesAsync (C:\projects\LFM\node_modules\@angular\compiler\bundles\compiler.umd.js:23931:47)
    at CodeGenerator.codegen (C:\projects\LFM\node_modules\@angular\compiler-cli\src\codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (C:\projects\LFM\node_modules\@angular\compiler-cli\src\ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (C:\projects\LFM\node_modules\@ngtools\webpack\src\plugin.js:386:44)

Help me please!

**Comment by atais** [comment]
would you say its done with #31?
