### ISSUE TITLE
meet one problem

### ISSUE THREAD

**Issue by DongWJ** [atais/ng2-eonasdan-datetimepicker#4]
### but i meet a problem.
`Uncaught (in promise): Error: Error in ./TestBaseComponent class TestBaseComponent - inline template:30:23 caused by: this.dpElement.datetimepicker is not a function`

### vendor.ts
`import 'eonasdan-bootstrap-datetimepicker';`

### .module.ts
`import { NgModule }      from '@angular/core';
import { CommonModule }       from '@angular/common';
import {TestBaseComponent} from "./test-base.component";
import { BrowserModule } from '@angular/platform-browser';
import {A2Edatetimepicker} from 'ng2-eonasdan-datetimepicker';
@NgModule({
    imports: [CommonModule,BrowserModule,A2Edatetimepicker],
    declarations: [TestBaseComponent],
    providers: [],  //服务
    exports:  [A2Edatetimepicker,TestBaseComponent]
})
export class TestBaseModule { }`

### .component.ts
`import { Component,OnInit} from '@angular/core';
let template = require('./test-base.component.html');
@Component({
    template: template
})
export class TestBaseComponent implements OnInit{
    a2eOptions = {
        format: "DD.MM.YYYY",
    };

    ngOnInit(){}

}`

### .html
`<div>
        <h4 style="color: red">日历</h4>
        <div class="form-group">
            <div class="input-group">
                <input class="form-control"
                       a2e-datetimepicker
                       [date]="dateTo"
                       [options]="a2eOptions"
                       (onChange)="dateToChange($event)"
                       (onClick)="dateClick()"/>
                <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span></span>
            </div>
        </div>
    </div>`

**Comment by atais** [comment]
you do not need to export the `A2Edatetimepicker` in your module.
try looking at the example plunker.

**Comment by DongWJ** [comment]
this is my feature module.
at the begining i am not  export the A2Edatetimepicker, only import in my feature  module.

the error always is ‘this.dpElement.datetimepicker is not a function’.

‘npm install ng2-eonasdan-datetimepicker -save’  is my  install way.

**Comment by DongWJ** [comment]
core.umd.js?e2a5:3468 Error: Uncaught (in promise): Error: Error in ./TestBaseComponent class TestBaseComponent - inline template:30:23 caused by: this.dpElement.datetimepicker is not a function
    at resolvePromise (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:418:31)
    at eval (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:395:13)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:192:28)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6242:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:191:34)
    at Zone.run (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:85:43)
    at eval (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:451:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:225:37)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6233:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:224:42)
    at Zone.runTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:125:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:357:35)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:297:25)
  -------------   Elapsed: 1137 ms; At: Tue Dec 13 2016 10:56:56 GMT+0800 (中国标准时间)   -------------  
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2657:2), <anonymous>:64:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:202:49)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:139:39)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:449:14)
    at resolvePromise (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:413:21)
    at eval (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:395:13)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2669:29)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:192:28)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6242:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:191:34)
    at Zone.run (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:85:43)
    at eval (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:451:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:225:37)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6233:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:224:42)
    at Zone.runTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:125:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:357:35)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:297:25)
  -------------   Elapsed: 0 ms; At: Tue Dec 13 2016 10:56:56 GMT+0800 (中国标准时间)   -------------  
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2657:2), <anonymous>:64:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:202:49)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:139:39)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:449:14)
    at ZoneAwarePromise.then (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:525:17)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2647:22)
    at new ZoneAwarePromise (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:467:29)
    at Router.runNavigate (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2593:20)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2584:71)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:192:28)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6242:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:191:34)
    at Zone.run (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:85:43)
    at eval (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:451:57)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:225:37)
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6233:41)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:224:42)
    at Zone.runTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:125:47)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:357:35)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:297:25)
  -------------   Elapsed: 2102 ms; At: Tue Dec 13 2016 10:56:54 GMT+0800 (中国标准时间)   -------------  
    at Object.onScheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2657:2), <anonymous>:64:22)
    at ZoneDelegate.scheduleTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:202:49)
    at Zone.scheduleMicroTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:139:39)
    at scheduleResolveOrReject (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:449:14)
    at ZoneAwarePromise.then (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:525:17)
    at Router.scheduleNavigation (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2584:38)
    at Router.navigateByUrl (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:2528:29)
    at RouterLinkWithHref.onClick (eval at <anonymous> (http://localhost:8090/vendor.js:222:2), <anonymous>:3201:25)
    at DebugAppView._View_MainComponent0._handle_click_18_0 (MainComponent.ngfactory.js:646:45)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:9698:28)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:208:2), <anonymous>:1877:40)
    at eval (eval at <anonymous> (http://localhost:8090/vendor.js:208:2), <anonymous>:1990:115)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:192:28)
    at Object.onInvoke (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6242:41)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:191:34)
    at Zone.runGuarded (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:99:47)
    at NgZoneImpl.runInnerGuarded (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6271:82)
    at NgZone.runGuarded (eval at <anonymous> (http://localhost:8090/vendor.js:100:2), <anonymous>:6504:77)
    at HTMLAnchorElement.outsideHandler (eval at <anonymous> (http://localhost:8090/vendor.js:208:2), <anonymous>:1990:83)
    at ZoneDelegate.invokeTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:225:37)
    at Zone.runTask (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:125:47)
    at HTMLAnchorElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:8090/polyfills.js:2651:2), <anonymous>:293:33)

**Comment by atais** [comment]
you need a dirty import in your test like I did in plunker.
With webpack I do not have this problem.

**Comment by shripadgodse** [comment]
@DongWJ is issue solved ? if yes, please let me know the solution. I am also facing same problem.

**Comment by Nasty94** [comment]
can you clarify what was the solution?  I tried the advices above and in the links, but still have same error:

core.es5.js?0445:1223 ERROR TypeError: this.dpElement.datetimepicker is not a function
    at DateTimePickerDirective.ngOnInit (eval at 635 (app.js:796), <anonymous>:75:24)
    at checkAndUpdateDirectiveInline (eval at <anonymous> (vendor.js:20), <anonymous>:11037:19)
    at checkAndUpdateNodeInline (eval at <anonymous> (vendor.js:20), <anonymous>:12533:17)
    at checkAndUpdateNode (eval at <anonymous> (vendor.js:20), <anonymous>:12472:16)
    at prodCheckAndUpdateNode (eval at <anonymous> (vendor.js:20), <anonymous>:13166:5)
    at Object.eval [as updateDirectives] (VisitorsComponent.ngfactory.js:2107)
    at Object.updateDirectives (eval at <anonymous> (vendor.js:20), <anonymous>:12923:72)
    at checkAndUpdateView (eval at <anonymous> (vendor.js:20), <anonymous>:12439:14)
    at callViewAction (eval at <anonymous> (vendor.js:20), <anonymous>:12804:21)
    at execComponentViewsAction (eval at <anonymous> (vendor.js:20), <anonymous>:12736:13)
    at checkAndUpdateView (eval at <anonymous> (vendor.js:20), <anonymous>:12445:5)
    at callViewAction (eval at <anonymous> (vendor.js:20), <anonymous>:12804:21)
    at execEmbeddedViewsAction (eval at <anonymous> (vendor.js:20), <anonymous>:12762:17)
    at checkAndUpdateView (eval at <anonymous> (vendor.js:20), <anonymous>:12440:5)
    at callViewAction (eval at <anonymous> (vendor.js:20), <anonymous>:12804:21)
